# Generated by Django 5.2.5 on 2026-08-26 14:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(db_index=True, default='', editable=False, max_length=20, unique=True)),
                ('device_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop Computer / PC'), ('Printer', 'Printer / Scanner'), ('CCTV', 'CCTV Camera / DVR'), ('UPS', 'UPS / Power Inverter'), ('Xerox', 'Xerox / Copier Machine'), ('Projector', 'Projector'), ('Other', 'Other Technical Device')], default='Laptop', max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('asset_number', models.CharField(blank=True, default='', max_length=100)),
                ('physical_condition', models.TextField(blank=True, default='', help_text='e.g. Scratches on lid, minor dent, good condition')),
                ('accessories', models.TextField(blank=True, default='', help_text='e.g. Charger, Power Cable, Bag, Mouse')),
                ('complaint', models.TextField(help_text="Customer's reported problem")),
                ('initial_diagnosis', models.TextField(blank=True, default='', help_text='Initial technical findings')),
                ('technician_notes', models.TextField(blank=True, default='', help_text='Internal notes')),
                ('priority', models.CharField(choices=[('Low', 'Low Priority'), ('Medium', 'Medium Priority'), ('High', 'High Priority'), ('Urgent', 'Urgent / Express Service')], default='Medium', max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending (Received)'), ('In Progress', 'In Progress (Diagnosis/Work)'), ('Completed', 'Completed (Ready for Delivery)'), ('Delivered', 'Delivered (Collected by Customer)'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to='accounts.staffprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_services', to='accounts.staffprofile')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('Pending', 'Pending (Received)'), ('In Progress', 'In Progress (Diagnosis/Work)'), ('Completed', 'Completed (Ready for Delivery)'), ('Delivered', 'Delivered (Collected by Customer)'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('Pending', 'Pending (Received)'), ('In Progress', 'In Progress (Diagnosis/Work)'), ('Completed', 'Completed (Ready for Delivery)'), ('Delivered', 'Delivered (Collected by Customer)'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='services.service')),
            ],
            options={
                'verbose_name': 'Service History',
                'verbose_name_plural': 'Service History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Progress Update',
                'verbose_name_plural': 'Service Progress Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
