# Generated by Django 5.2.5 on 2026-08-26 14:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Spare Part', 'Spare Part (Screen, Keyboard, RAM, SSD, etc.)'), ('Motherboard Chip', 'Chip Level / IC / Component'), ('Consumable', 'Consumables (Thermal paste, solder, cleaner)'), ('Third-Party', 'Third-Party / Specialist Service'), ('Transport', 'Courier / Transport Expense'), ('Other', 'Other Service Expense')], default='Spare Part', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Expense',
                'verbose_name_plural': 'Service Expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('labor_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('parts_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sub_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='services.service')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Inward Created', 'Inward Created'), ('Status Change', 'Status Change'), ('Work Progress', 'Work Progress Update'), ('Expense Added', 'Expense / Part Added'), ('Payment Received', 'Payment Received'), ('Invoice Generated', 'Invoice Generated'), ('Delivered', 'Device Delivered'), ('Cancelled', 'Service Cancelled'), ('Other', 'Other Action')], default='Other', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Ledger Entry',
                'verbose_name_plural': 'Service Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI (GPay / PhonePe / Paytm)'), ('Card', 'Debit / Credit Card'), ('Bank Transfer', 'Net Banking / NEFT'), ('Other', 'Other Method')], default='Cash', max_length=50)),
                ('reference_number', models.CharField(blank=True, default='', help_text='UPI Ref / Transaction ID / Receipt No', max_length=100)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Payment',
                'verbose_name_plural': 'Service Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
